/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_diegocruz;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author dfcm9
 */
public class MainAdmin extends javax.swing.JFrame {
    
    int contventaid = 0;
    ArrayList <Vehiculo> carros = new ArrayList();
    ArrayList <Vendedor> vendedores = new ArrayList();
    ArrayList <Cliente> clientes = new ArrayList();
    ArrayList <Venta> ventasrealizadas = new ArrayList();
    ArrayList <Venta> ventasfull = new ArrayList();
    ArrayList<Cliente> tempclientes = new ArrayList();
    ArrayList<Vendedor> tempvendedores = new ArrayList();
    ArrayList<Vehiculo> tempcarros = new ArrayList();
    Random ran = new Random();
    String abc = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

    /**
     * Creates new form MainAdmin
     */
    public MainAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jb_addcarro = new javax.swing.JButton();
        tf_marcaveh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_modveh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        js_anioveh = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        tf_precioveh = new javax.swing.JTextField();
        tf_color = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_nomvend = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        js_carrosvend = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        tf_dineroven = new javax.swing.JTextField();
        jb_addvend = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tf_nomcliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        js_edadcliente = new javax.swing.JSpinner();
        tf_profcliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        js_carroscompcli = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        tf_sueldocli = new javax.swing.JTextField();
        jb_addcliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cb_carros = new javax.swing.JComboBox<>();
        cb_clientes = new javax.swing.JComboBox<>();
        cb_vendedores = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jb_hacerventa = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_archivos = new javax.swing.JTextArea();
        jb_abrirarchivo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_dia = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_general = new javax.swing.JTree();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jb_generarreporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AdministraCarros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 17, 300, 38));

        jTabbedPane1.setBackground(new java.awt.Color(102, 153, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jb_addcarro.setText("Agregar Vehiculo");
        jb_addcarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addcarroMouseClicked(evt);
            }
        });

        jLabel2.setText("Marca");

        jLabel3.setText("Seleccione Color");

        jLabel4.setText("Modelo");

        jLabel5.setText("Año");

        js_anioveh.setModel(new javax.swing.SpinnerNumberModel(2023, 1945, null, 1));

        jLabel6.setText("Precio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_modveh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_marcaveh, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(216, 216, 216)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_precioveh, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_anioveh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jb_addcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_marcaveh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_anioveh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_color, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_precioveh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_modveh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jb_addcarro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("Agregar Vehiculo", jPanel2);

        jLabel8.setText("Nombre");

        jLabel9.setText("Carros Vendidos");

        js_carrosvend.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel10.setText("Dinero Generado");

        jb_addvend.setText("Agregar Vendedor");
        jb_addvend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addvendMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_carrosvend, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nomvend, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(178, 178, 178)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_dineroven, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jb_addvend, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nomvend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_dineroven, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_carrosvend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jb_addvend, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("Agregar Vendedor", jPanel3);

        jLabel11.setText("Nombre");

        jLabel12.setText("Edad");

        js_edadcliente.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));

        jLabel13.setText("Profesion");

        jLabel14.setText("Cantidad de Carros Comprados");

        js_carroscompcli.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel15.setText("Sueldo Disponible");

        jb_addcliente.setText("Agregar Cliente");
        jb_addcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_addclienteMouseClicked(evt);
            }
        });
        jb_addcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_addclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nomcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_profcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_edadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(js_carroscompcli, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_sueldocli, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(199, 199, 199))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jb_addcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nomcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_carroscompcli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_edadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_sueldocli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_profcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jb_addcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Agregar Cliente", jPanel4);

        jLabel7.setText("Seleccione Vendedor");

        jLabel16.setText("Seleccione Cliente");

        jLabel17.setText("Seleccione Carro a Comprar");

        jb_hacerventa.setText("Hacer Venta");
        jb_hacerventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_hacerventaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cb_carros, 0, 302, Short.MAX_VALUE)
                        .addComponent(cb_clientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_vendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jb_hacerventa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_vendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_carros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jb_hacerventa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("Hacer Venta", jPanel5);

        ta_archivos.setColumns(20);
        ta_archivos.setRows(5);
        jScrollPane1.setViewportView(ta_archivos);

        jb_abrirarchivo.setText("Abrir Archivo");
        jb_abrirarchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_abrirarchivoMouseClicked(evt);
            }
        });

        jButton2.setText("Guardar Archivo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jb_abrirarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_abrirarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Abrir Archivo", jPanel6);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Dia");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Venta");
        treeNode1.add(treeNode2);
        jt_dia.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_dia);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Admin");
        jt_general.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_general);

        jLabel18.setText("Informacion del Dia");

        jLabel19.setText("Sistema General");

        jb_generarreporte.setText("Generar Reporte de Ventas Diarias");
        jb_generarreporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_generarreporteMouseClicked(evt);
            }
        });
        jb_generarreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_generarreporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_generarreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)))
                .addGap(133, 133, 133)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_generarreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Arboles", jPanel7);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 950, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_addcarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addcarroMouseClicked
        File archivocar = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            String ma, mo, id;
            String color;
            int anio;
            double prec;
            ma = tf_marcaveh.getText();
            mo = tf_modveh.getText();
            color = tf_color.getText();
            anio = Integer.parseInt(js_anioveh.getValue().toString());
            prec = Double.parseDouble(tf_precioveh.getText());
            id = genid();
            Vehiculo x = new Vehiculo(ma,mo,id,color,anio,prec);
            carros.add(x);
            JOptionPane.showMessageDialog(null, "Carro Agregado exitosamente!");
            archivocar = new File ("./carros.txt");
            fw = new FileWriter(archivocar, true);
            bw = new BufferedWriter(fw);
            bw.write("[\n\t"+ma+",\n\t"+mo+",\n\t"+anio+",\n\t"+color+",\n\t"+prec+",\n\t"+id+",\n];\n");
            bw.flush();
            tf_marcaveh.setText("");
            tf_modveh.setText("");
            js_anioveh.setValue(2023);
            tf_color.setText("");
            tf_precioveh.setText("");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
            e.printStackTrace();
        }
        
        
        try {
            fw.close();
            bw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jb_addcarroMouseClicked

    private void jb_addvendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addvendMouseClicked
        File archivovend = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            String nom;
            int carvend;
            double dinero;
            nom =  tf_nomvend.getText();
            carvend = Integer.parseInt(js_carrosvend.getValue().toString());
            dinero = Double.parseDouble(tf_dineroven.getText());
            Vendedor y = new Vendedor (nom,carvend,dinero);
            vendedores.add(y);
            JOptionPane.showMessageDialog(null, "Vendedor Agregado exitosamente!");
            archivovend = new File ("./vendedores.txt");
            fw = new FileWriter(archivovend, true);
            bw = new BufferedWriter(fw);
            bw.write("[\n\t"+nom+",\n\t"+carvend+",\n\t"+dinero+",\n];\n");
            bw.flush();
            tf_nomvend.setText("");
            js_carrosvend.setValue(0);
            tf_dineroven.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
            e.printStackTrace();
        }
        
        try {
            fw.close();
            bw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jb_addvendMouseClicked

    private void jb_addclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_addclienteMouseClicked
        File archivocli = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        try {
            String nom, prof;
            int edad, carroscomp;
            double sueldo;
            
            nom = tf_nomcliente.getText();
            prof = tf_profcliente.getText();
            edad = Integer.parseInt(js_edadcliente.getValue().toString());
            carroscomp = Integer.parseInt(js_carroscompcli.getValue().toString());
            sueldo = Double.parseDouble(tf_sueldocli.getText());
            Cliente w = new Cliente (nom,prof,edad,carroscomp,sueldo);
            clientes.add(w);
            JOptionPane.showMessageDialog(null, "Cliente Agregado exitosamente!");
            archivocli = new File ("./clientescompradores.txt");
            fw = new FileWriter(archivocli, true);
            bw = new BufferedWriter(fw);
            bw.write("[\n\t"+nom+",\n\t"+prof+",\n\t"+edad+",\n\t"+carroscomp+",\n\t"+sueldo+",\n];\n");
            bw.flush();
            tf_nomcliente.setText("");
            tf_profcliente.setText("");
            js_edadcliente.setValue(18);
            js_carroscompcli.setValue(0);
            tf_dineroven.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
            e.printStackTrace();
        }
        
        try {
            fw.close();
            bw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jb_addclienteMouseClicked

    private void jb_addclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_addclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_addclienteActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex() == 3){
            RellenarCarros();
            RellenarCompradores();
            RellenarVendedores();
            
            
            
        }
        
        if (jTabbedPane1.getSelectedIndex() == 5){
            RellenarCarros();
            RellenarCompradores();
            RellenarVendedores();
            
            String carro = "Vehiculos";
            String clientes = "Clientes";
            String vendedores = "Vendedores";
            DefaultTreeModel modeloARBOL
                    = (DefaultTreeModel) jt_general.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(carro);
            
            for (Vehiculo tempcarro : tempcarros) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(tempcarro);
                n.add(p);
                
            }
            
            DefaultMutableTreeNode o = new DefaultMutableTreeNode(clientes);
            
            for (Cliente tempcliente : tempclientes) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(tempcliente);
                o.add(p);
                
            }
            
            DefaultMutableTreeNode v = new DefaultMutableTreeNode(vendedores);
            
            for (Vendedor tempvendedor : tempvendedores) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(tempvendedor);
                v.add(p);
                
            }
            
            raiz.add(n);
            raiz.add(o);
            raiz.add(v);
            
            modeloARBOL.reload();
        }
        
        if (jTabbedPane1.getSelectedIndex() == 5){
            DefaultTreeModel modeloARBOL
                    = (DefaultTreeModel) jt_general.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jb_hacerventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_hacerventaMouseClicked
        
        
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        try {
            String nomven, nomcomp, carroid;
            Venta x = new Venta ();
            x.setCarvend((Vehiculo) cb_carros.getSelectedItem());
            x.setComprador((Cliente) cb_clientes.getSelectedItem());
            x.setCoste(((Vehiculo) cb_carros.getSelectedItem()).getPrecio());
            x.setVendedor((Vendedor) cb_vendedores.getSelectedItem());
            nomven = ((Vendedor) cb_vendedores.getSelectedItem()).getNombre();
            nomcomp = ((Cliente) cb_clientes.getSelectedItem()).getNombre();
            carroid = ((Vehiculo) cb_carros.getSelectedItem()).getID();
            tempclientes.get(cb_clientes.getSelectedIndex()).setCantcarros(tempclientes.get(cb_clientes.getSelectedIndex()).getCantcarros()+1);
            tempvendedores.get(cb_vendedores.getSelectedIndex()).setCancarros(tempvendedores.get(cb_vendedores.getSelectedIndex()).getCancarros()+1);
            tempvendedores.get(cb_vendedores.getSelectedIndex()).setCandinero(tempvendedores.get(cb_vendedores.getSelectedIndex()).getCandinero()+((Vehiculo)cb_carros.getSelectedItem()).getPrecio());
            ventasrealizadas.add(x);
            archivo = new File ("./ventasgenerales.txt");
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            bw.write("[\n\t"+nomcomp+",\n\t"+nomven+",\n\t"+carroid+",\n];\n");
            bw.flush();
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
            e.printStackTrace();
        }
        
        try {
            fw.close();
            bw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
        
        try {
            archivo = new File ("./clientescompradores.txt");
            fw = new FileWriter(archivo, false);
            bw = new BufferedWriter(fw);
            for (Cliente tc : tempclientes) {
                bw.write("[\n\t"+tc.getNombre()+",\n\t"+tc.getProf()+",\n\t"+tc.getEdad()+",\n\t"+tc.getCantcarros()+",\n\t"+tc.getSueldo()+",\n];\n");
                
            }
            bw.flush();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            archivo = new File ("./vendedores.txt");
            fw = new FileWriter(archivo, false);
            bw = new BufferedWriter(fw);
            for (Vendedor tv : tempvendedores) {
                
                bw.write("[\n\t"+tv.getNombre()+",\n\t"+tv.getCancarros()+",\n\t"+tv.getCandinero()+",\n];\n");
            }
            bw.flush();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        RellenarCarros();
        RellenarCompradores();
        RellenarVendedores();
        JOptionPane.showMessageDialog(this, "La venta se ha realizado exitosamente!");
       
    }//GEN-LAST:event_jb_hacerventaMouseClicked

    private void jb_abrirarchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_abrirarchivoMouseClicked
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        ta_archivos.setText("");
        try {
            
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro = 
                    new FileNameExtensionFilter(
                            "Archivos de Texto", "txt");
            jfc.setFileFilter(filtro);        
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION)
            {
               fichero = jfc.getSelectedFile();
               fr = new FileReader(fichero);
               br=new BufferedReader(fr);
               String linea;
               ta_archivos.setText("");
               while(  (linea=br.readLine()) !=null  ){                    
                    ta_archivos.append(linea);
                    ta_archivos.append("\n");
                }
            } //fin if
            
        } catch (Exception e) {
        }
        
        try {
            br.close();
            fr.close();
        } catch (IOException ex) {
        }
       
    }//GEN-LAST:event_jb_abrirarchivoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = 
                    new FileNameExtensionFilter(
                            "Archivos de Texto", "txt");
        jfc.addChoosableFileFilter(filtro); 
        int seleccion = jfc.showSaveDialog(this);        
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
             try {
                 
                  File fichero=null;
                if (jfc.getFileFilter().getDescription().equals(
                        "Archivos de Texto")) {
                    fichero = 
                        new File(jfc.getSelectedFile().getPath()+".txt");
                }else{
                    fichero = jfc.getSelectedFile();
                }                             
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);
                bw.write(ta_archivos.getText());
                ta_archivos.setText("");
                bw.flush();         
                JOptionPane.showMessageDialog(this, "El Archivo se guardo exitosamente!");  
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                    bw.close();
                    fw.close();
                } catch (IOException ex) {
           }                     
        }//fin IF
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_generarreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_generarreporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_generarreporteActionPerformed

    private void jb_generarreporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_generarreporteMouseClicked
        String nombre = JOptionPane.showInputDialog(this, "Nombre del Archivo a Crear:");
        File archivoventas = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        try {
            archivoventas = new File ("./"+nombre+".txt");
            fw = new FileWriter(archivoventas, true);
            bw = new BufferedWriter(fw);
            for (Venta ventreal : ventasrealizadas) {
                bw.write("[\n\t"+contventaid+",\n\t"+ventreal.getComprador().getNombre()+",\n\t"+ventreal.getVendedor().getNombre()+",\n\t"+ventreal.getCarvend().getID()+",\n];\n");
                contventaid++;
            }
            bw.flush();
            JOptionPane.showMessageDialog(this, "El archivo diario se creo exitosamente!");
            contventaid = 0;
            ventasrealizadas = new ArrayList();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            fw.close();
            bw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jb_generarreporteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }
    
    public void RellenarCarros(){
        tempcarros = new ArrayList();
        
        File fcarros = null;
        FileReader fr = null;
        BufferedReader br = null;
        Scanner sc = null;
        int count = 0;
                
        //Carro bw.write("[\n\t"+ma+",\n\t"+mo+",\n\t"+anio+",\n\t"+prec+",\n];\n");
        //Vendedor bw.write("[\n\t"+nom+",\n\t"+carvend+",\n\t"+dinero+",\n];\n");
        //Cliente bw.write("[\n\t"+nom+",\n\t"+prof+",\n\t"+edad+",\n\t"+carroscomp+",\n\t"+sueldo+",\n];\n");
        
        
        try {
            fcarros = new File ("./carros.txt");
            fr = new FileReader (fcarros);
            br = new BufferedReader(fr);
            
            if (fcarros.exists()){
                String mar, mod, color, anio, precio, id, temporal;
                
                        
                DefaultComboBoxModel modelobox = new DefaultComboBoxModel();
                String linea;
                while ( (linea = br.readLine()) != null ) { 
                    mar = br.readLine();
                    mar = mar.trim();
                    mar = mar.substring(0,mar.length()-1);
                    mod = br.readLine();
                    mod = mod.trim();
                    mod = mod.substring(0,mod.length()-1);
                    anio = br.readLine();
                    anio = anio.trim();
                    anio = anio.substring(0,anio.length()-1);
                    color = br.readLine();
                    color = color.trim();
                    color = color.substring(0,color.length()-1);
                    precio = br.readLine();
                    precio = precio.trim();
                    precio = precio.substring(0, precio.length()-1);
                    id = br.readLine();
                    id = id.trim();
                    id = id.substring(0, id.length()-1);
                    temporal = br.readLine();
                    Vehiculo x = new Vehiculo (mar, mod, id, color, Integer.parseInt(anio), Double.parseDouble(precio));
                    tempcarros.add(x);
                    modelobox.addElement(x);
                }
                cb_carros.setModel(modelobox);
            }
            br.close();
            fr.close();

            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error, puede que alguno de los archivos no exista.");
            e.printStackTrace();
        }
        
        
        
    }
    
    public void RellenarVendedores(){
        tempvendedores = new ArrayList();
        File fvend = null;
        FileReader fr = null;
        BufferedReader br = null;
        Scanner sc = null;
        int count = 0;
        
        //Carro bw.write("[\n\t"+ma+",\n\t"+mo+",\n\t"+anio+",\n\t"+prec+",\n];\n");
        //Vendedor bw.write("[\n\t"+nom+",\n\t"+carvend+",\n\t"+dinero+",\n];\n");
        //Cliente bw.write("[\n\t"+nom+",\n\t"+prof+",\n\t"+edad+",\n\t"+carroscomp+",\n\t"+sueldo+",\n];\n");
        
        
        try {
            fvend = new File ("./vendedores.txt");
            fr = new FileReader (fvend);
            br = new BufferedReader(fr);
            
            if (fvend.exists()){
                String nom, carvend, dingen, temporal;
                
                        
                DefaultComboBoxModel modelobox = new DefaultComboBoxModel();
                String linea;
                while ( (linea = br.readLine()) != null ) { 
                    nom = br.readLine();
                    nom = nom.trim();
                    nom = nom.substring(0,nom.length()-1);
                    carvend = br.readLine();
                    carvend = carvend.trim();
                    carvend = carvend.substring(0,carvend.length()-1);
                    dingen = br.readLine();
                    dingen = dingen.trim();
                    dingen = dingen.substring(0,dingen.length()-1);
                    temporal = br.readLine();
                    Vendedor x = new Vendedor (nom, Integer.parseInt(carvend),Double.parseDouble(dingen));
                    tempvendedores.add(x);
                    modelobox.addElement(x);
                }
                cb_vendedores.setModel(modelobox);
            }
            
            br.close();
            fr.close();
            

            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error, puede que alguno de los archivos no exista.");
            e.printStackTrace();
        }
        
    }
    
    public void RellenarCompradores(){
        tempclientes = new ArrayList();
        File fclien = null;
        FileReader fr = null;
        BufferedReader br = null;
        Scanner sc = null;
        int count = 0;
        
        //Carro bw.write("[\n\t"+ma+",\n\t"+mo+",\n\t"+anio+",\n\t"+prec+",\n];\n");
        //Vendedor bw.write("[\n\t"+nom+",\n\t"+carvend+",\n\t"+dinero+",\n];\n");
        //Cliente bw.write("[\n\t"+nom+",\n\t"+prof+",\n\t"+edad+",\n\t"+carroscomp+",\n\t"+sueldo+",\n];\n");
        
        
        try {
            fclien = new File ("./clientescompradores.txt");
            fr = new FileReader (fclien);
            br = new BufferedReader(fr);
            
            if (fclien.exists()){
                String nom, ed, prof, cantcar, sueldo, temporal;
                
                        
                DefaultComboBoxModel modelobox = new DefaultComboBoxModel();
                String linea;
                while ( (linea = br.readLine()) != null ) { 
                    nom = br.readLine();
                    nom = nom.trim();
                    nom = nom.substring(0,nom.length()-1);
                    prof = br.readLine();
                    prof = prof.trim();
                    prof = prof.substring(0,prof.length()-1);
                    ed = br.readLine();
                    ed = ed.trim();
                    ed = ed.substring(0,ed.length()-1);
                    
                    cantcar = br.readLine();
                    cantcar = cantcar.trim();
                    cantcar = cantcar.substring(0,cantcar.length()-1);
                    sueldo = br.readLine();
                    sueldo = sueldo.trim();
                    sueldo = sueldo.substring(0,sueldo.length()-1);
                    temporal = br.readLine();
                    Cliente x = new Cliente(nom, prof, Integer.parseInt(ed), Integer.parseInt(cantcar), Double.parseDouble(sueldo));
                    tempclientes.add(x);
                    modelobox.addElement(x);
                }
                cb_clientes.setModel(modelobox);
            }
            br.close();
            fr.close();
            

            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error, puede que alguno de los archivos no exista.");
            e.printStackTrace();
        }
        
    }
    
    public void RellenarVentas(){
        ventasrealizadas = new ArrayList();
        File fventas = null;
        FileReader fr = null;
        BufferedReader br = null;
        Scanner sc = null;
        int count = 0;
        
        
        
        try {
            fventas = new File ("./ventasgenerales.txt");
            fr = new FileReader (fventas);
            br = new BufferedReader(fr);
            
            if (fventas.exists()){
                String nomcomp, nomvend, id, temporal;
                
                        
                
                String linea;
                while ( (linea = br.readLine()) != null ) { 
                    nomcomp = br.readLine();
                    nomcomp = nomcomp.trim();
                    nomcomp = nomcomp.substring(0,nomcomp.length()-1);
                    nomvend = br.readLine();
                    nomvend = nomvend.trim();
                    nomvend = nomvend.substring(0,nomvend.length()-1);
                    id = br.readLine();
                    id = id.trim();
                    id = id.substring(0,id.length()-1);
                    
                    temporal = br.readLine();
                    Vehiculo a = new Vehiculo();
                    Venta x = new Venta();
                    ventasrealizadas.add(x);
                    
                }
                
            }
            br.close();
            fr.close();
            

            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error, puede que alguno de los archivos no exista.");
            e.printStackTrace();
        }
        
        
    }
    
    public String genid(){
        String temp = "";
        for (int i = 0; i < 4; i++) {
            temp+=Integer.toString(ran.nextInt(10));
            
        }
        for (int j = 0; j < 4; j++) {
            temp+=abc.charAt(ran.nextInt(abc.length()));
            
        }
        return temp;
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_carros;
    private javax.swing.JComboBox<String> cb_clientes;
    private javax.swing.JComboBox<String> cb_vendedores;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_abrirarchivo;
    private javax.swing.JButton jb_addcarro;
    private javax.swing.JButton jb_addcliente;
    private javax.swing.JButton jb_addvend;
    private javax.swing.JButton jb_generarreporte;
    private javax.swing.JButton jb_hacerventa;
    private javax.swing.JSpinner js_anioveh;
    private javax.swing.JSpinner js_carroscompcli;
    private javax.swing.JSpinner js_carrosvend;
    private javax.swing.JSpinner js_edadcliente;
    private javax.swing.JTree jt_dia;
    private javax.swing.JTree jt_general;
    private javax.swing.JTextArea ta_archivos;
    private javax.swing.JTextField tf_color;
    private javax.swing.JTextField tf_dineroven;
    private javax.swing.JTextField tf_marcaveh;
    private javax.swing.JTextField tf_modveh;
    private javax.swing.JTextField tf_nomcliente;
    private javax.swing.JTextField tf_nomvend;
    private javax.swing.JTextField tf_precioveh;
    private javax.swing.JTextField tf_profcliente;
    private javax.swing.JTextField tf_sueldocli;
    // End of variables declaration//GEN-END:variables
}
